name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services using Docker Compose
        working-directory: ./event_service
        run: |
          docker-compose up -d

      - name: Wait for MySQL to be ready
        run: |
          until docker-compose exec -T mysql_container mysqladmin ping -h"127.0.0.1" --silent; do
            echo 'Waiting for MySQL to be ready...';
            sleep 5;
          done

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./event_service
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run migrations
        working-directory: ./event_service
        run: |
          poetry run alembic upgrade head

      - name: Run tests
        working-directory: ./event_service
        env:
          DATABASE_URL: mysql+pymysql://user:@127.0.0.1/test_db
        run: |
          poetry run pytest

      - name: Shut down services
        run: |
          docker-compose down
