name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./event_service
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS test_db;"
          mysql -e "CREATE USER 'user'@'localhost' IDENTIFIED BY '';"
          mysql -e "GRANT ALL PRIVILEGES ON test_db.* TO 'user'@'localhost';"
          mysql -e "FLUSH PRIVILEGES;"

      - name: Run tests
        working-directory: ./event_service
        run: |
          poetry run pytest
